### ISSUE TITLE
angel never kills logger processes

### ISSUE THREAD

**Issue by tcrayford** [MichaelXavier/Angel#29]
You mentioned this in a discussion, and it seems pertinent to fix it here. Here is a fun piece of output (these are all zombie processes that had previously spawned a logger, but then became zombied when I (cleanly) restarted `angel`:

```
ps aux | grep sudo | wc -l
19099
```

**Comment by tcrayford** [comment]
Did this ever get fixed?

**Comment by MichaelXavier** [comment]
Just tested it out and evidently not. While the process is running I see many defunct logger instances. I'll have a look.

**Comment by tcrayford** [comment]
(I'm still on a version of angel from before this was around)

**Comment by MichaelXavier** [comment]
From the looks of the code it makes no effort whatsoever to reap those processes. Angel's code is a bit of a disaster so in addition to fixing this, maybe this will prompt me to pick work back up on my rewrite, Seraph.

**Comment by MichaelXavier** [comment]
Ok this should be sorted out now. In my local testing this seems to work. Do you think you could test out the 29-logger-zombies branch?

**Comment by MichaelXavier** [comment]
Time's up. Merged.

**Comment by tcrayford** [comment]
@MichaelXavier sorry. Been traveling and don't really do things to production that aren't more complicated than releasing new versions of a webapp whilst out :(

**Comment by MichaelXavier** [comment]
Don't sweat it. I'm reasonably convinced what I did works. I like to get consensus from people experiencing the issue when possible but it isn't required. If there are issues, that's what patch versions are for.
