### ISSUE TITLE
Option to make angel logging less verbose

### ISSUE THREAD

**Issue by rickynils** [MichaelXavier/Angel#38]
I miss an option to turn off angel's logging of the `ENDED`, `WAITING`, `RESTART`, `START`, `Spawning ...` and `RUNNING` entries. Basically I would like to be able to tell angel to only log failures, or possibly just one line when a command is started (without the whole env printed).

My use-case is a large number of short-lived diagnostic checks that for the moment produce a lot of noise in the logs due to angel's verboseness.

**Comment by MichaelXavier** [comment]
This sounds useful. How does a numeric verbosity flag sound? -v0, -v1, -v2 etc? I could also see a token-based flag -v debug, -v info, etc.

What would get logged at each level? Would -v0 log absolutely nothing? Does the highest level (v2? v3) log more than Angel is currently logging?

**Comment by rickynils** [comment]
Numeric verbosity sounds great. Maybe `-v0` logs only failures, `-v1` logs only a single line per spawned process (like `spawned <processname>`, where processname is the id in the config file), `-v2` logs like today, all state transitions. I don't know if there is any interesting debug info beyond that (maybe some process context, but I don't know what). I'm not sure if the environment logging would belong to `-v2` or `-v3`.

**Comment by MichaelXavier** [comment]
Hi, Sorry for the delay. I've finally gotten around to this. Would you be able to give the `log-level` branch a try in the next few days and let me know if this works for you? If so, I can merge it, clean up and cut a release.

**Comment by rickynils** [comment]
@MichaelXavier I seem to get a test failure during build, but other than that this seems to work fine! Thanks!

**Comment by MichaelXavier** [comment]
This is merged and on hackage as version 0.5.2. Thanks.
