### ISSUE TITLE
Travis build fails for GHC 7.10 build

### ISSUE THREAD

**Issue by ignesco** [MichaelXavier/Angel#47]
The travis build just for GHC 7.10 fails with a cabal config error.  See extract below

$ cabal test

cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.22.2.0, now Cabal-1.22.5.0).

**Comment by ignesco** [comment]
There is a fix for this on branch 47-travis-7.10-build-failure-03 - it bumps up the cabal version to 1.24 for the GHC 7.10 build only.

What are people's opinion on this fix?

**Comment by MichaelXavier** [comment]
I've got no problem with using 1.24 :+1:

**Comment by ignesco** [comment]
Sorry, forgot to close this issue after merge.
